### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by V10lator** [b-jesch/script.service.hypercon#1]
```
2020-09-07 10:14:49.869 T:3735643008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'during'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.hypercon/service.py", line 232, in <module>
                                                hyperion = Hyperion()
                                              File "/storage/.kodi/addons/script.service.hypercon/service.py", line 74, in __init__
                                                self.start()
                                              File "/storage/.kodi/addons/script.service.hypercon/service.py", line 203, in start
                                                self.eventHandler(force=True)
                                              File "/storage/.kodi/addons/script.service.hypercon/service.py", line 193, in eventHandler
                                                self.effectHandler(self.opt_menuMode)
                                              File "/storage/.kodi/addons/script.service.hypercon/service.py", line 152, in effectHandler
                                                self.connection.clearAll()
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/connection.py", line 54, in clearAll
                                                kl.writeLog('success: %s %s' % self.send('{"command": "clearall"}'))
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/connection.py", line 16, in send
                                                self.__ws = websocket.create_connection(self.__url, timeout=3)
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/websocket/_core.py", line 502, in create_connection
                                                websock.connect(url, **options)
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/websocket/_core.py", line 222, in connect
                                                self.handshake_response = handshake(self.sock, *addrs, **options)
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/websocket/_handshake.py", line 69, in handshake
                                                status, resp = _get_resp_headers(sock)
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/websocket/_handshake.py", line 138, in _get_resp_headers
                                                status, resp_headers, status_message = read_headers(sock)
                                              File "/storage/.kodi/addons/script.service.hypercon/resources/lib/websocket/_http.py", line 306, in read_headers
                                                status = int(status_info[1])
                                            ValueError: invalid literal for int() with base 10: 'during'
                                            -->End of Python script error report<--
```

**Comment by b-jesch** [comment]
Exception handling now raise a WebSocketException on malformed headers.
